embeddings {
  tensor_name: "id:00520"
  metadata_path: "00520/id\\metadata.tsv"
  tensor_path: "00520/id\\tensors.tsv"
}
embeddings {
  tensor_name: "month:00520"
  metadata_path: "00520/month\\metadata.tsv"
  tensor_path: "00520/month\\tensors.tsv"
}
