embeddings {
  tensor_name: "id:02600"
  metadata_path: "02600/id\\metadata.tsv"
  tensor_path: "02600/id\\tensors.tsv"
}
embeddings {
  tensor_name: "month:02600"
  metadata_path: "02600/month\\metadata.tsv"
  tensor_path: "02600/month\\tensors.tsv"
}
embeddings {
  tensor_name: "day_of_week:02600"
  metadata_path: "02600/day_of_week\\metadata.tsv"
  tensor_path: "02600/day_of_week\\tensors.tsv"
}
embeddings {
  tensor_name: "day_of_year:02600"
  metadata_path: "02600/day_of_year\\metadata.tsv"
  tensor_path: "02600/day_of_year\\tensors.tsv"
}
embeddings {
  tensor_name: "quarter:02600"
  metadata_path: "02600/quarter\\metadata.tsv"
  tensor_path: "02600/quarter\\tensors.tsv"
}
