embeddings {
  tensor_name: "currency_type:00377"
  metadata_path: "00377/currency_type\\metadata.tsv"
  tensor_path: "00377/currency_type\\tensors.tsv"
}
embeddings {
  tensor_name: "month:00377"
  metadata_path: "00377/month\\metadata.tsv"
  tensor_path: "00377/month\\tensors.tsv"
}
embeddings {
  tensor_name: "day_of_week:00377"
  metadata_path: "00377/day_of_week\\metadata.tsv"
  tensor_path: "00377/day_of_week\\tensors.tsv"
}
embeddings {
  tensor_name: "day_of_year:00377"
  metadata_path: "00377/day_of_year\\metadata.tsv"
  tensor_path: "00377/day_of_year\\tensors.tsv"
}
embeddings {
  tensor_name: "quarter:00377"
  metadata_path: "00377/quarter\\metadata.tsv"
  tensor_path: "00377/quarter\\tensors.tsv"
}
