embeddings {
  tensor_name: "currency_type:00990"
  metadata_path: "00990/currency_type\\metadata.tsv"
  tensor_path: "00990/currency_type\\tensors.tsv"
}
embeddings {
  tensor_name: "month:00990"
  metadata_path: "00990/month\\metadata.tsv"
  tensor_path: "00990/month\\tensors.tsv"
}
embeddings {
  tensor_name: "day_of_week:00990"
  metadata_path: "00990/day_of_week\\metadata.tsv"
  tensor_path: "00990/day_of_week\\tensors.tsv"
}
embeddings {
  tensor_name: "day_of_year:00990"
  metadata_path: "00990/day_of_year\\metadata.tsv"
  tensor_path: "00990/day_of_year\\tensors.tsv"
}
embeddings {
  tensor_name: "quarter:00990"
  metadata_path: "00990/quarter\\metadata.tsv"
  tensor_path: "00990/quarter\\tensors.tsv"
}
