embeddings {
  tensor_name: "id:00377"
  metadata_path: "00377/id\\metadata.tsv"
  tensor_path: "00377/id\\tensors.tsv"
}
embeddings {
  tensor_name: "month:00377"
  metadata_path: "00377/month\\metadata.tsv"
  tensor_path: "00377/month\\tensors.tsv"
}
